### PR TITLE
refactor(babel-plugin): work with latest babel

### PR DESCRIPTION
**Pull request by mgcrea**
Had to refactor the plugin to work with latest babel. Might be interesting.

I haven't found a way to add parameters annotations back yet. Looks like we're stuck on https://github.com/babel/babel/issues/1351 for now.

### CODE REVIEW

**Comment by gdi2290** [comment]
:+1:

**Comment by mgcrea** [comment]
Took the time to write a proper PR to babel regarding angular2 constructor decorators, but it got closed right away :sob: https://github.com/babel/babel/pull/2138. I'll maintain a fork until pluggable parsers are available.

**Comment by shuhei** [comment]
Thanks for your PR :smile: 

So, the parameter decorators don't work with the latest babel now. I'll keep this open until some way to solve it become possible.

**Comment by shuhei** [comment]
Merging because the current master doesn't work with the current babel/angular. Thanks!

**Pull request merged**
