### PR TITLE
Drop support of parameter decorators

### LINKED ISSUE #16: Drop support of parameter decorators
The babel team is going to forbid people from monkey-patching the parser.

https://github.com/babel/babel/pull/3204

## DI for directives

- `@Attribute`: Not so necessary? Can we use `@Input` instead of this?
- `@Query`: Replaceable with `@ContentChild` and `@ContentChildren`?
- `@ViewQuery`: Replaceable with `@ViewChild` and `@ContentChildren`?
- [`@Host`](https://angular.io/docs/ts/latest/api/core/HostMetadata-class.html): The host directive's providers http://victorsavkin.com/post/126514197956/dependency-injection-in-angular-1-and-angular-2

## Pure DI

- `@Inject`: Probably be necessary for advanced developers?
- `@Optional`: Probably necessary for advanced developers?
- `@Self`: Not so necessary for app developers? The same element's providers http://victorsavkin.com/post/126514197956/dependency-injection-in-angular-1-and-angular-2
- `@SkipSelf`: Not so necessary for app developers?

https://angular.io/docs/ts/latest/api/#!?apiFilter=metadata

### PR DESCRIPTION
**Pull request by shuhei**
Fixes #16
- [x] Drop parameter decorators support
- [x] Add integration tests for alternatives of all the parameter decorators
- [x] Document how to achieve goals without using parameter decorators

### CODE REVIEW

**Comment by ahmehri** [comment]
@shuhei the modifications of this PR are so important. Unfortunately they are not yet released (if you check the repo page, the old README is the one that's always displayed).

I spent a lot of time figuring out the ESLint error `... is defined but never used no-unused-vars`. Because this PR is not released, I was so confused why I'm still getting the error despite using your patch which clearly indicates that it supports **Decorators for constructor parameters**. I even went to clone the linked  **babel-angular2-app** to check how you did the integration just to be surprised later when I found out that even in your example app, the error persists:
`1:38  error  'Attribute' is defined but never used  no-unused-vars`

I recommend to release this PR to avoid such confusion and update the linked app example as well.

**Comment by shuhei** [comment]
@ahmehri The eslint error is not an issue of this repo but of babel and babel-eslint. Parameter decorators were removed because of the monkey patch prevention in babel, but were added again because babel started supporting the syntax.

I made an PR for the eslint error, but it's not merged yet. https://github.com/babel/babel-eslint/pull/373

**Comment by ahmehri** [comment]
As a user of your plugin, not finding all what you mentioned in the README will make me think that parameter decorators are supported for the moment. I suggest to update the README to make things clear for users.

**Comment by shuhei** [comment]
@ahmehri OK, created [an issue for it](https://github.com/shuhei/babel-plugin-angular2-annotations/issues/29) because I think *issues* should be in GitHub *Issues* instead of in README.

**Pull request merged**
