### PR TITLE
Babel 6

### PR DESCRIPTION
**Pull request by shuhei**
https://github.com/shuhei/babel-plugin-angular2-annotations/issues/6

- [x] Update dependencies
- [x] Parameter decorators
- [x] Type decorators
- [x] Release of https://github.com/babel/babel/pull/2697
- [x] Use legacy decorators plugin https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy
- [x] Build script without `babel-plugin`
- [x] Update README ([presets/plugins order](https://github.com/babel/babel/issues/2648))

### CODE REVIEW

**Comment by calebboyd** [comment]
https://phabricator.babeljs.io/T2645

**Comment by shuhei** [comment]
@calebboyd Thanks. I'm gonna go with babel 5.x until the new decorator proposal is implemented.

**Comment by calebboyd** [comment]
Great, good to know

**Comment by amcdnl** [comment]
For the most part the community is using this until Babel finishes Decorators for v6 - https://www.npmjs.com/package/babel-plugin-transform-decorators-legacy

**Pull request merged**
